### ISSUE TITLE
constant crashes

### ISSUE THREAD

**Issue by littleblack111** [hyprwm/hyprpolkitagent#11]
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.19437.1732180855000000.zip](https://github.com/user-attachments/files/17867950/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.19437.1732180855000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.19514.1732180856000000.zip](https://github.com/user-attachments/files/17867952/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.19514.1732180856000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.19549.1732180856000000.zip](https://github.com/user-attachments/files/17867955/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.19549.1732180856000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.19584.1732180857000000.zip](https://github.com/user-attachments/files/17867957/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.19584.1732180857000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.76306.1732181105000000.zip](https://github.com/user-attachments/files/17867958/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.76306.1732181105000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.76347.1732181106000000.zip](https://github.com/user-attachments/files/17867959/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.76347.1732181106000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.76376.1732181106000000.zip](https://github.com/user-attachments/files/17867960/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.76376.1732181106000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.76417.1732181107000000.zip](https://github.com/user-attachments/files/17867961/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.76417.1732181107000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.76436.1732181107000000.zip](https://github.com/user-attachments/files/17867962/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.76436.1732181107000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.77689.1732181120000000.zip](https://github.com/user-attachments/files/17867963/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.77689.1732181120000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.77732.1732181120000000.zip](https://github.com/user-attachments/files/17867964/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.77732.1732181120000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.77770.1732181121000000.zip](https://github.com/user-attachments/files/17867965/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.77770.1732181121000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.77795.1732181121000000.zip](https://github.com/user-attachments/files/17867966/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.77795.1732181121000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.82790.1732181315000000.zip](https://github.com/user-attachments/files/17867967/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.82790.1732181315000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.82863.1732181316000000.zip](https://github.com/user-attachments/files/17867968/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.82863.1732181316000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.82900.1732181316000000.zip](https://github.com/user-attachments/files/17867969/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.82900.1732181316000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.82929.1732181316000000.zip](https://github.com/user-attachments/files/17867970/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.82929.1732181316000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.82970.1732181317000000.zip](https://github.com/user-attachments/files/17867971/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.82970.1732181317000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.86535.1732181345000000.zip](https://github.com/user-attachments/files/17867972/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.86535.1732181345000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.86582.1732181346000000.zip](https://github.com/user-attachments/files/17867973/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.86582.1732181346000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.86630.1732181346000000.zip](https://github.com/user-attachments/files/17867974/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.86630.1732181346000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.86654.1732181346000000.zip](https://github.com/user-attachments/files/17867975/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.86654.1732181346000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.86678.1732181347000000.zip](https://github.com/user-attachments/files/17867976/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.86678.1732181347000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.86706.1732181347000000.zip](https://github.com/user-attachments/files/17867978/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.86706.1732181347000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.86727.1732181348000000.zip](https://github.com/user-attachments/files/17867979/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.86727.1732181348000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.103852.1732181435000000.zip](https://github.com/user-attachments/files/17867981/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.103852.1732181435000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.104046.1732181435000000.zip](https://github.com/user-attachments/files/17867982/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.104046.1732181435000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.104230.1732181435000000.zip](https://github.com/user-attachments/files/17867984/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.104230.1732181435000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.104344.1732181436000000.zip](https://github.com/user-attachments/files/17867985/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.104344.1732181436000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.104510.1732181436000000.zip](https://github.com/user-attachments/files/17867986/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.104510.1732181436000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.139174.1732181554000000.zip](https://github.com/user-attachments/files/17867987/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.139174.1732181554000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.139294.1732181554000000.zip](https://github.com/user-attachments/files/17867988/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.139294.1732181554000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.139443.1732181554000000.zip](https://github.com/user-attachments/files/17867989/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.139443.1732181554000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.139569.1732181555000000.zip](https://github.com/user-attachments/files/17867990/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.139569.1732181555000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.139683.1732181555000000.zip](https://github.com/user-attachments/files/17867992/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.139683.1732181555000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.145445.1732181571000000.zip](https://github.com/user-attachments/files/17867993/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.145445.1732181571000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.145554.1732181571000000.zip](https://github.com/user-attachments/files/17867994/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.145554.1732181571000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.145698.1732181571000000.zip](https://github.com/user-attachments/files/17867995/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.145698.1732181571000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.145828.1732181571000000.zip](https://github.com/user-attachments/files/17867996/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.145828.1732181571000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.239450.1732181887000000.zip](https://github.com/user-attachments/files/17867997/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.239450.1732181887000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.239587.1732181887000000.zip](https://github.com/user-attachments/files/17867998/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.239587.1732181887000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.239723.1732181887000000.zip](https://github.com/user-attachments/files/17867999/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.239723.1732181887000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.239859.1732181888000000.zip](https://github.com/user-attachments/files/17868000/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.239859.1732181888000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.297457.1732182066000000.zip](https://github.com/user-attachments/files/17868001/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.297457.1732182066000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.297620.1732182067000000.zip](https://github.com/user-attachments/files/17868003/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.297620.1732182067000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.297721.1732182067000000.zip](https://github.com/user-attachments/files/17868004/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.297721.1732182067000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.297860.1732182067000000.zip](https://github.com/user-attachments/files/17868005/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.297860.1732182067000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.298019.1732182068000000.zip](https://github.com/user-attachments/files/17868006/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.298019.1732182068000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.489435.1732182752000000.zip](https://github.com/user-attachments/files/17868007/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.489435.1732182752000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.489688.1732182752000000.zip](https://github.com/user-attachments/files/17868008/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.489688.1732182752000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.489794.1732182752000000.zip](https://github.com/user-attachments/files/17868009/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.489794.1732182752000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.489925.1732182753000000.zip](https://github.com/user-attachments/files/17868010/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.489925.1732182753000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.490025.1732182753000000.zip](https://github.com/user-attachments/files/17868011/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.490025.1732182753000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.973501.1732233991000000.zip](https://github.com/user-attachments/files/17868012/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.973501.1732233991000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.973546.1732233991000000.zip](https://github.com/user-attachments/files/17868013/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.973546.1732233991000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.973584.1732233991000000.zip](https://github.com/user-attachments/files/17868014/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.973584.1732233991000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.973615.1732233992000000.zip](https://github.com/user-attachments/files/17868015/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.973615.1732233992000000.zip)
[core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.973653.1732233992000000.zip](https://github.com/user-attachments/files/17868016/core.hyprpolkitagent.1000.2564b3a93ee04678bcceaba4029ee5b2.973653.1732233992000000.zip)

Note: i renamed the coredump files from .zst to .zip cuz github doesn't allow .zst

**Comment by vaxerski** [comment]
coredump files are useless to anyone but you. Get a debug stacktrace from them

**Comment by littleblack111** [comment]
[gdb.txt](https://github.com/user-attachments/files/17870700/gdb.txt)

**Comment by vaxerski** [comment]
`This application failed to start because no Qt platform plugin could be initialized.`

Do you have the dependencies...? qt6-wayland, qqc2-desktop-style.

**Comment by littleblack111** [comment]
not sure, just using sysd as wiki suggest(`exec-once = systemctl --user start hyprpolkitagent`)

**Comment by vaxerski** [comment]
`dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE`

**Comment by littleblack111** [comment]
i cant repro rn as its not crashing atm. not sure how did i get it to crash before

**Comment by vaxerski** [comment]
closing then
