### ISSUE TITLE
no window popping up after starting the service

### ISSUE THREAD

**Issue by dawnchan030920** [hyprwm/hyprpolkitagent#13]
After starting the service(which is checked using systemctl status) and `sudo` a graphical program, the window doesn't pop up, but still the command line asking for my password and giving me the **authorization protocol not specified** error.
I am running on nixos with hyprland.

**Comment by dawnchan030920** [comment]
> how did you fixed? 

Sorry to disappoint you, but I actually I didn't fix it. I just suppose that it be not related to hyprland and close the issue. If you think that hyprland  is suspicious, feel free to reopen it!

**Comment by Matemix** [comment]
I think you had the same problem as me right now, i built the project from source, andafter cmale --install it dose not copy the main.qml ant those other files anywhere. I asked chatGPT where i should put those, but what he said did not work. My problem is i never worked with QT before, and i have no idear what to do. For infos I am using Ubuntu 25.10 with the newest Hyprland packages as of today, and this is the output of hyprpolkitagent:

Spawning qml prompt 
QQmlApplicationEngine failed to load component 
qrc:qt/qml/hpa/main.qlm: module "org.hyprland.style" is not installed
