### ISSUE TITLE
[bug] Ignores qt styles

### ISSUE THREAD

**Issue by enk-it** [hyprwm/hyprpolkitagent#2]
I'm using `adwaita-qt5` for qt applications. And most of qt apps uses this theme (i've set it with qt5ct), but hyprpolkitagent ignores it and tries to use it's default value (`org.kde.desktop`). I've tried setting `QT_QUICK_CONTROLS_STYLE` to 'Adwaita-Dark' and `Adwait-dark` but it just says:
`qrc:/qt/qml/hpa/qml/main.qml: module "Adwaita-Dark" is not installed`.
But if i set it to some default qt style, Material for example, it runs flawlessly.

**Comment by vaxerski** [comment]
`QT_QUICK_CONTROLS_STYLE` is _not_ a theme. It's a theme provider. Install qqc2-desktop-style.
