### ISSUE TITLE
dbus error missing D-Bus Service Section

### ISSUE THREAD

**Issue by ctilley83** [hyprwm/hyprpolkitagent#5]
When compiling from git, cmake install places an identical service file in ```/usr/share/dbus-1/services``` and ```usr/lib/systemd/user```. This causes the following error:

Oct 31 16:52:38 linuxbox dbus-broker-launch[2832]: Missing 'D-Bus Service' section in service file '/usr/share//dbus-1/services/hyprpolkitagent.service'

It seems like systemd manages the service and not dbus so is it ok to delete the service file in the dbus-1 folder?

**Comment by vaxerski** [comment]
I don't know dbus well enough. MRs welcome

**Comment by sevy2011** [comment]
I looked at other polkit implementations (`polkit-gnome`, `polkit-kde-agent`) and they don't implement such a file at all.
There exists a DBUS-Service file `/usr/share/dbus-1/system-servicesorg.freedesktop.PolicyKit1.service` installed by the `polkit` package which I suspect does the job.

After deleting the file in question I don't get any errors in `journalctl` or `dmesg` and testing with `pkcheck` does work flawlessly
