### ISSUE TITLE
Window too small

### ISSUE THREAD

**Issue by superNWHG** [hyprwm/hyprpolkitagent#7]
When trying to use hyprpolkitagent with a command thats too long, it will show the first few characters of the command, then ..., then the last few characters.
Because of this, I would expect the text to be small enough to fit in the window.
In the screenshot below, you can see this is clearly not the case:
![image](https://github.com/user-attachments/assets/0dafe1b1-142c-43b7-8e6f-f599334107bc)
Also, I can't resize the window to see the full window but I can fullscreen the window.

**Comment by vaxerski** [comment]
oopsie
