### ISSUE TITLE
[disscussion] why not having this embedded directly in Hyprland

### ISSUE THREAD

**Issue by zefr0x** [hyprwm/hyprpolkitagent#8]
I'm with modularity, but some things just don't feel like should be separated.

One compelling reason might be security, where not every application can spoof a window to be like the authentication GUI.

As of my knowledge the only DE that have implemented it in that way is Gnome. Regardless of all the controversy around them, I think they implemented it in the most secure way.

---

We already have [hyprlock](https://github.com/hyprwm/hyprlock) code for password prompt that could be used as a base. However, it will need some work, since there is no real interactive GUI thing that has been embedded before in the core Hyprland AFAK

**Comment by vaxerski** [comment]
because thats not how linux works.

> implemented it in the most secure way

there is no security argument here - if something can "spoof" being a popup window like that one, it can also run `rm -rf ~` and other (arguably worse) things.

**Comment by zefr0x** [comment]
> if something can "spoof" being a popup window like that one, it can also run `rm -rf ~` and other (arguably worse) things.

unless its a sandboxed application

But any way I don't have a strong compelling reason, you know better.

**Comment by vaxerski** [comment]
> unless it's a sandboxed application

sure... you could make that argument, but it's kinda like saying "dont click the big green download button on an ad"

the app doesn't know what exactly you are running if it's sandboxed so it's unlikely it will look exactly like the real deal.
